### ISSUE TITLE
Select specific targets for update

### ISSUE THREAD

**Issue by mrballcb** [ReadyTalk/vault-admin#11]
The full run of the vault-admin takes quite some time as it processes each json file one at a time.  There are times where you might only update a single file.  This feature request is to add a cli option with arg to tell the vault-admin to only update policies, or only update entities, or only update groups, or only update jenkins tokens.

**Comment by bartlettc22** [comment]
I've opened a PR to add concurrency which is something we've been wanting for quite a while.  This should help speed up performance.  Allowing individual components to be run could be accomplished but I think it would take away from the idea that the configuration repo reflects exactly what is in Vault.  I could see things potentially getting out of sync easier due to human error.
